export const types = {
  AUTH: {
    LOGIN: "AUTH.LOGIN",
    PASSWORD: "AUTH.PASSWORD",
    EMAIL_VALIDATION: {
      SUCCESS: "AUTH.EMAIL_VALIDATION.EMAIL_SUCCESS",
      ERROR: "AUTH.EMAIL_VALIDATION.EMAIL_ERROR",
    },
    PASSWORD_VALIDATION: {
      SUCCESS: "AUTH.PASSWORD_VALIDATION.SUCCESS",
      ERROR: "AUTH.PASSWORD_VALIDATION.ERROR",
    },
    DATA: {
      RESET: "AUTH.DATA.RESET",
    },
  },
  NOTIFICATION: {
    SUCCESS: "NOTIFICATION.SUCCESS",
    RESET: "NOTIFICATION.RESET",
  },
  ERRORS: {
    RESET: "ERRORS.RESET",
  },
};
